services:
  # Node.js Express application
  app:
    build: .
    container_name: express-app
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    depends_on:
      - db # Ensure that the database is started before the app

  # PostgreSQL 15
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
  frontend:
    build:
      context: ./client
    container_name: react-frontend
    ports:
      - "3001:3000"
    depends_on:
      - app

volumes:
  postgres_data:
    driver: local

